# Site settings
title: hooonko
email: hooon.ko@gmail.com
description: "hooonko's github io blog!"
baseurl: ""
url: "http://hooonko.github.io"
twitter_username: hooonko
github_username:  hooonko
facebook_username:  hooonko

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
